### ISSUE TITLE
Your usage of goroutine is wrong

### ISSUE THREAD

**Issue by mattn** [chzyer/flow#1]
``` go
func main() {
    f := flow.New()
    go func() {
        f.Add(1)
        defer f.Done()
        println("exit")
    }()
    f.Wait() // wait will capture signals
}
```

This is not correct because f.Wait() may finish before f.Add(1). It should be below.

``` go
func main() {
    f := flow.New()
    f.Add(1)
    go func() {
        defer f.Done()
        println("exit")
    }()
    f.Wait() // wait will capture signals
}
```

**Comment by chzyer** [comment]
Hi!
For sync.WaitGroup, you are right. But flow.Wait() has a different semantic that it waits kill signal or a stop call "flow.Stop()". "flow.Stop()" will called automatic if somewhere call "flow.Done()" and its reference equals to 0.
So that example is right. Thanks for dig that.

**Comment by mattn** [comment]
Ah, sorry. Then below should be blocked?

``` go
f := flow.New()
f.Wait()
```

**Comment by chzyer** [comment]
Yes, but we can call "Close()" manually to stop blocking.
